#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
FAMILY_ROOT = REPO / "benchmark_blueprints" / "families" / "pr-review-fanout-remediation"
VERIFIER_DATA = REPO / "verifier_data" / "pr-review-fanout-remediation"
SCORER = REPO / "verifiers" / "pr-review-fanout-remediation" / "score_review_fanout.py"


def overlay_tree(src: Path, dst: Path) -> None:
    if not src.exists():
        return
    for path in src.rglob("*"):
        rel = path.relative_to(src)
        target = dst / rel
        if path.is_dir():
            target.mkdir(parents=True, exist_ok=True)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy(path, target)


def make_oracle(ws: Path, variant: str) -> None:
    overlay_tree(VERIFIER_DATA / variant / "oracle", ws)


def make_empty(ws: Path, variant: str) -> None:
    return


def make_code_only(ws: Path, variant: str) -> None:
    overlay_tree(VERIFIER_DATA / variant / "oracle" / "src", ws / "src")
    overlay_tree(VERIFIER_DATA / variant / "oracle" / "tests", ws / "tests")
    overlay_tree(VERIFIER_DATA / variant / "oracle" / "docs", ws / "docs")


def make_wrong_triage(ws: Path, variant: str) -> None:
    make_oracle(ws, variant)
    triage_path = ws / "artifacts/review/thread_triage.json"
    triage = json.loads(triage_path.read_text())
    for entry in triage:
        if entry["thread_id"] == "T-214-02":
            entry["disposition"] = "actionable"
            entry.pop("duplicate_of", None)
            entry["rationale"] = "treated as a separate open code fix"
    triage_path.write_text(json.dumps(triage, indent=2, sort_keys=True) + "\n")


def make_generic_replies(ws: Path, variant: str) -> None:
    make_oracle(ws, variant)
    reply_path = ws / "artifacts/review/reply_draft.md"
    reply_path.write_text(
        "# Review Replies\n\nAll comments are addressed in this patch. Code, tests, and docs now align.\n"
    )


def make_delete_tests(ws: Path, variant: str) -> None:
    make_oracle(ws, variant)
    locked_test = ws / "tests/test_approval_router.py"
    locked_test.write_text(locked_test.read_text() + "\n# tampered\n")


TRAJECTORIES = [
    ("01_oracle", make_oracle, "Oracle (full pass)"),
    ("02_empty", make_empty, "Empty (no submission)"),
    ("03_code_only", make_code_only, "Code-only shortcut"),
    ("04_wrong_triage", make_wrong_triage, "Wrong triage on duplicate thread"),
    ("05_generic_replies", make_generic_replies, "Generic replies without thread mapping"),
    ("06_delete_tests", make_delete_tests, "Delete-tests adversarial"),
]


def score_workspace(variant: str, builder) -> dict:
    with tempfile.TemporaryDirectory(prefix=f"review_vmx_{variant}_") as tmp:
        tmp_path = Path(tmp)
        ws = tmp_path / "workspace"
        shutil.copytree(FAMILY_ROOT / "workspace_bundle" / variant, ws)
        builder(ws, variant)
        result_path = tmp_path / "verify_result.json"
        env = os.environ.copy()
        env.update(
            {
                "AGENT_WS": str(ws),
                "VERIFIER_DATA": str(VERIFIER_DATA),
                "VARIANT_ID": variant,
                "RESULT_FILE": str(result_path),
            }
        )
        subprocess.run(
            [sys.executable, str(SCORER)],
            env=env,
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        return json.loads(result_path.read_text())


def derive_G(result: dict) -> float:
    h = 1.0 if result.get("integrity_flag", 0) == 0 else 0.0
    i = 1.0 if result.get("milestones", {}).get("M1_localization", False) else 0.0
    s = float(result.get("M_training", 0.0))
    return round(0.15 * h + 0.25 * i + 0.60 * s, 4)


def derive_R(result: dict) -> float:
    h = int(result.get("integrity_flag", 0))
    m_agg = float(result.get("milestone_vector", {}).get("M_aggregate", 0.0))
    if result.get("pass", False):
        return 1.0
    return round(0.6 * m_agg - 0.6 * h, 4)


def derive_S_TTC(result: dict) -> int:
    passed = 1 if result.get("pass", False) else 0
    m_agg = float(result.get("milestone_vector", {}).get("M_aggregate", 0.0))
    integrity = int(result.get("integrity_flag", 0))
    g_score = derive_G(result)
    return int(round(1000 * passed + 100 * m_agg - 100 * integrity + 10 * g_score))


def matrix_markdown(variant: str, rows: list[dict[str, object]]) -> str:
    lines = [
        f"# §5 verification matrix — {variant}",
        "",
        f"Generated by `verifiers/pr-review-fanout-remediation/run_verification_matrix.py --variant {variant}`.",
        "",
        "| trajectory | P_benchmark | M_training | G | R | S_TTC | integrity | pass | ceilings |",
        "|---|---:|---:|---:|---:|---:|---:|---|---|",
    ]
    for row in rows:
        ceilings = ",".join(row["ceilings"]) if row["ceilings"] else "—"
        if row["integrity_rules"]:
            ceilings = f"H={','.join(row['integrity_rules'])}"
        lines.append(
            f"| {row['label']} | {row['P_benchmark']} | {row['M_training']:.4f} | "
            f"{row['G']:.3f} | {row['R']:.3f} | {row['S_TTC']} | {row['integrity']} | "
            f"{row['passed']} | {ceilings} |"
        )
    lines.extend(
        [
            "",
            "## Notes",
            "",
            "- Oracle should clear 90+ with all milestones true.",
            "- Empty should score 0.",
            "- Code-only should cap low because triage and reply artifacts are missing.",
            "- Wrong-triage should cap at or below 25.",
            "- Delete-tests should raise `integrity_flag = 1` and zero M3/M4/M5.",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--variant", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    rows: list[dict[str, object]] = []
    for _, builder, label in TRAJECTORIES:
        result = score_workspace(args.variant, builder)
        rows.append(
            {
                "label": label,
                "P_benchmark": int(result["P_benchmark"]),
                "M_training": float(result["M_training"]),
                "G": derive_G(result),
                "R": derive_R(result),
                "S_TTC": derive_S_TTC(result),
                "integrity": int(result["integrity_flag"]),
                "passed": bool(result["pass"]),
                "ceilings": list(result.get("ceilings_applied", [])),
                "integrity_rules": list(result.get("integrity_rules_fired", [])),
            }
        )

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(matrix_markdown(args.variant, rows))
    return 0


if __name__ == "__main__":
    sys.exit(main())
