#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
FAMILY = REPO / "benchmark_blueprints" / "families" / "responses-tool-schema-cutover"
WORKSPACE_BUNDLE = FAMILY / "workspace_bundle"
VERIFIER_DATA = REPO / "verifier_data" / "responses-tool-schema-cutover"
SCORER = REPO / "verifiers" / "responses-tool-schema-cutover" / "score_responses_cutover.py"


def overlay_tree(src: Path, dst: Path) -> None:
    if not src.exists():
        return
    for path in src.rglob("*"):
        rel = path.relative_to(src)
        target = dst / rel
        if path.is_dir():
            target.mkdir(parents=True, exist_ok=True)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, target)


def make_oracle(ws: Path, variant: str) -> None:
    overlay_tree(VERIFIER_DATA / variant / "oracle", ws)


def make_empty(ws: Path, variant: str) -> None:
    return


def make_grounding_stripped(ws: Path, variant: str) -> None:
    overlay_tree(VERIFIER_DATA / variant / "oracle" / "gateway", ws / "gateway")
    overlay_tree(VERIFIER_DATA / variant / "oracle" / "tests", ws / "tests")


def make_adapter_only(ws: Path, variant: str) -> None:
    overlay_tree(VERIFIER_DATA / variant / "oracle" / "gateway", ws / "gateway")
    reducer = ws / "gateway" / "reducer.py"
    broken = reducer.read_text()
    if "FIXED_REDUCER_MARKER" in broken:
        return
    # Restore the broken reducer by copying from baseline workspace after
    # the oracle overlay landed for adapter.py.
    baseline = WORKSPACE_BUNDLE / variant / "gateway" / "reducer.py"
    reducer.write_text(baseline.read_text())


def make_chronology_blind(ws: Path, variant: str) -> None:
    overlay_tree(VERIFIER_DATA / variant / "oracle", ws)
    reducer = ws / "gateway" / "reducer.py"
    reducer.write_text(
        reducer.read_text().replace(
            "insert_at = call_positions[call_id] + 1\n",
            "insert_at = len(transcript)\n",
        )
    )


def make_delete_tests(ws: Path, variant: str) -> None:
    make_oracle(ws, variant)
    shim = ws / "pytest.py"
    shim.write_text("raise SystemExit(0)\n")


TRAJECTORIES = [
    ("01_oracle", make_oracle, "Oracle (full pass)"),
    ("02_empty", make_empty, "Empty (no submission)"),
    ("03_grounding_stripped", make_grounding_stripped, "RAWR grounding_stripped"),
    ("04_adapter_only", make_adapter_only, "Adapter-only shortcut"),
    ("05_chronology_blind", make_chronology_blind, "Chronology-blind fix"),
    ("06_delete_tests", make_delete_tests, "Delete-tests adversarial"),
]


def score_workspace(variant: str, builder) -> dict:
    with tempfile.TemporaryDirectory(prefix=f"responses_matrix_{variant}_") as tmp:
        tmp_path = Path(tmp)
        ws = tmp_path / "workspace"
        shutil.copytree(WORKSPACE_BUNDLE / variant, ws)
        builder(ws, variant)
        result_path = tmp_path / "verify_result.json"
        env = os.environ.copy()
        env.update(
            {
                "AGENT_WS": str(ws),
                "VERIFIER_DATA": str(VERIFIER_DATA),
                "VARIANT_ID": variant,
                "RESULT_FILE": str(result_path),
                "PYTHONDONTWRITEBYTECODE": "1",
            }
        )
        subprocess.run(
            [sys.executable, str(SCORER)],
            check=True,
            env=env,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        return json.loads(result_path.read_text())


def derive_G(result: dict) -> float:
    h = 1.0 if result.get("integrity_flag", 0) == 0 else 0.0
    i = 1.0 if result.get("milestones", {}).get("M1_localization", False) else 0.0
    s = float(result.get("M_training", 0.0))
    return round(0.15 * h + 0.25 * i + 0.60 * s, 4)


def derive_R(result: dict) -> float:
    if result.get("pass", False):
        return 1.0
    h = int(result.get("integrity_flag", 0))
    m_agg = float(result.get("milestone_vector", {}).get("M_aggregate", 0.0))
    return round(0.6 * m_agg - 0.6 * h, 4)


def derive_S_TTC(result: dict) -> int:
    P = 1 if result.get("pass", False) else 0
    h = int(result.get("integrity_flag", 0))
    m_agg = float(result.get("milestone_vector", {}).get("M_aggregate", 0.0))
    return int(round(1000 * P + 100 * m_agg - 100 * h + 10 * derive_G(result)))


def matrix_markdown(variant: str, rows: list[dict[str, object]]) -> str:
    lines = [
        f"# §5 verification matrix — {variant}",
        "",
        f"Generated by `verifiers/responses-tool-schema-cutover/run_verification_matrix.py --variant {variant}`.",
        "",
        "| trajectory | P_benchmark | M_training | G | R | S_TTC | integrity | pass | ceilings |",
        "|---|---:|---:|---:|---:|---:|---:|---|---|",
    ]
    for row in rows:
        ceilings = ",".join(row["ceilings"]) if row["ceilings"] else "—"
        if row["integrity_rules"]:
            ceilings = f"H={','.join(row['integrity_rules'])}"
        lines.append(
            f"| {row['label']} | {row['P_benchmark']} | {row['M_training']:.4f} | "
            f"{row['G']:.3f} | {row['R']:.3f} | {row['S_TTC']} | {row['integrity']} | "
            f"{row['passed']} | {ceilings} |"
        )
    lines.extend(
        [
            "",
            "## Notes",
            "",
            "- Oracle should clear the full hidden replay suite and both non-code contract checks.",
            "- Empty should score 0 with `no_submission`.",
            "- RAWR grounding_stripped keeps code fixes but omits config/doc alignment, so `contract_drift` should cap it.",
            "- Adapter-only should hit `adapter_or_reducer_gap`.",
            "- Chronology-blind should fail the hidden replay oracle even if the visible shape looks close.",
            "- Delete-tests should raise `integrity_flag = 1` via `pytest_shim`.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--variant", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    rows = []
    for _, builder, label in TRAJECTORIES:
        result = score_workspace(args.variant, builder)
        rows.append(
            {
                "label": label,
                "P_benchmark": int(result["P_benchmark"]),
                "M_training": float(result["M_training"]),
                "G": derive_G(result),
                "R": derive_R(result),
                "S_TTC": derive_S_TTC(result),
                "integrity": int(result["integrity_flag"]),
                "passed": bool(result["pass"]),
                "ceilings": list(result.get("ceilings_applied", [])),
                "integrity_rules": list(result.get("integrity_rules_fired", [])),
            }
        )

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(matrix_markdown(args.variant, rows) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
