name: reusable-release
on:
  workflow_call:
    inputs:
      manifest_path:
        required: true
        type: string
      target_environment:
        required: true
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "legacy reusable contract"
