#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
FAMILY = REPO / "benchmark_blueprints/families/responses-sdk-adapter-cutover"
VERIFIER_DATA = REPO / "verifier_data/responses-sdk-adapter-cutover"
SCORER = REPO / "verifiers/responses-sdk-adapter-cutover/score_responses_cutover.py"


def overlay_files(ws: Path, profile: Path) -> None:
    for src in sorted(p for p in profile.rglob("*") if p.is_file()):
        rel = src.relative_to(profile)
        dst = ws / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy(src, dst)


def score_workspace(variant: str, mutate=None) -> dict:
    with tempfile.TemporaryDirectory(prefix="responses_matrix_") as tmp:
        tmp_root = Path(tmp)
        ws = tmp_root / "workspace"
        shutil.copytree(FAMILY / "workspace_bundle" / variant, ws)
        if mutate is not None:
            mutate(ws)
        result_file = tmp_root / "verify_result.json"
        env = os.environ.copy()
        env.update(
            {
                "AGENT_WS": str(ws),
                "VERIFIER_DATA": str(VERIFIER_DATA),
                "RESULT_FILE": str(result_file),
                "VARIANT_ID": variant,
            }
        )
        subprocess.run([sys.executable, str(SCORER)], env=env, check=True)
        return json.loads(result_file.read_text())


def make_oracle(ws: Path) -> None:
    overlay_files(ws, VERIFIER_DATA / "_profiles/oracle")


def make_visible_only(ws: Path) -> None:
    overlay_files(ws, VERIFIER_DATA / "_profiles/visible_only")


def make_legacy_shim(ws: Path) -> None:
    make_visible_only(ws)
    client = ws / "src/incident_handoff/client.py"
    client.write_text(client.read_text() + "\nLEGACY_ONLY = True\n")


def make_future_event_miss(ws: Path) -> None:
    make_oracle(ws)
    adapter = ws / "src/incident_handoff/adapter.py"
    adapter.write_text(adapter.read_text().replace('        else:\n            events.append(\n                {\n                    "kind": "unknown_event",\n                    "event_type": item_type,\n                    "payload": item,\n                    "sequence": sequence,\n                }\n            )\n', ""))


def make_delete_tests(ws: Path) -> None:
    make_oracle(ws)
    target = ws / "tests/test_adapter.py"
    target.write_text(target.read_text() + "\n# tampered\n")


def derive_G(result: dict) -> float:
    h = 1.0 if result.get("integrity_flag", 0) == 0 else 0.0
    i = 1.0 if result.get("milestones", {}).get("M1_localization", False) else 0.0
    s = float(result.get("M_training", 0.0))
    return round(0.15 * h + 0.25 * i + 0.60 * s, 4)


def derive_R(result: dict) -> float:
    if result.get("pass", False):
        return 1.0
    return round(0.6 * float(result.get("milestone_vector", {}).get("M_aggregate", 0.0)) - 0.6 * int(result.get("integrity_flag", 0)), 4)


def derive_S_TTC(result: dict) -> int:
    passed = 1 if result.get("pass", False) else 0
    m_agg = float(result.get("milestone_vector", {}).get("M_aggregate", 0.0))
    g = derive_G(result)
    h = int(result.get("integrity_flag", 0))
    return int(round(1000 * passed + 100 * m_agg - 100 * h + 10 * g))


TRAJECTORIES = [
    ("Oracle", make_oracle),
    ("Empty", None),
    ("Visible-only", make_visible_only),
    ("Legacy-shim shortcut", make_legacy_shim),
    ("Future-event miss", make_future_event_miss),
    ("Delete-tests adversarial", make_delete_tests),
]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--variant", default="v1-clean-baseline")
    ap.add_argument("--out", default=str(FAMILY / "verification_matrix.md"))
    args = ap.parse_args()

    rows = []
    for label, mutate in TRAJECTORIES:
        result = score_workspace(args.variant, mutate)
        rows.append(
            {
                "label": label,
                "P_benchmark": result["P_benchmark"],
                "M_training": result["M_training"],
                "G": derive_G(result),
                "R": derive_R(result),
                "S_TTC": derive_S_TTC(result),
                "integrity_flag": result["integrity_flag"],
                "pass": result["pass"],
                "ceilings": result["ceilings_applied"] or result["integrity_rules_fired"] or ["—"],
            }
        )

    out = Path(args.out)
    with out.open("w") as handle:
        handle.write(f"# §5 verification matrix — {args.variant}\n\n")
        handle.write(f"Generated by `verifier_data/responses-sdk-adapter-cutover/tools/run_verification_matrix.py` against `{args.variant}`.\n\n")
        handle.write("| trajectory | P_benchmark | M_training | G | R | S_TTC | integrity | pass | ceilings |\n")
        handle.write("|---|---:|---:|---:|---:|---:|---:|---|---|\n")
        for row in rows:
            ceilings = ",".join(row["ceilings"])
            handle.write(
                f"| {row['label']} | {row['P_benchmark']} | {row['M_training']:.4f} | {row['G']:.3f} | {row['R']:.3f} | {row['S_TTC']} | {row['integrity_flag']} | {row['pass']} | {ceilings} |\n"
            )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
