"""Publish only the independently accepted, untimed M1 numerical results."""
from pathlib import Path
import hashlib
import json

V2 = Path(__file__).resolve().parents[1]
OUT = V2 / 'results/review-response-20260927'
ACCEPT = V2 / 'p0/monitor/review-response-20260927/M1-Q-C0-PARENT-ACCEPTANCE-v1.json'
REDUCE = V2 / 'experiments/review-response-20260927/runs/m1-q-c0/reduction-repair-20260928T223230Z/RECEIPT.json'


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    accept = json.loads(ACCEPT.read_text())
    assert accept['status'] == 'ACCEPT_REVIEWED_NUMERICAL_RESULT_WITH_PERFORMANCE_NARROWING'
    for path, expected in accept['inputs_sha256'].items():
        assert sha(V2 / path) == expected, path
    result = json.loads(REDUCE.read_text())
    assert result['collection_admissible'] and result['outcome'] == 'FAIL'
    assert result['timing'] is False and result['seed'] == 20260929 and result['layers'] == 48
    specs = [
        ('lumo_fixed32_native', r'\sys{} / native', 'verify_outputs', 'published_state'),
        ('weaver_author_default', 'Weaver author-default', 'verification_outputs', 'accepted_replay_state'),
        ('weaver_aligned_local', 'Weaver aligned-local', 'verification_outputs', 'accepted_replay_state'),
        ('treewy_author_default', 'TreeWY author-default', 'fused_commit_verify_outputs', 'durable_state_after_commit_or_final_flush'),
    ]
    rows = []
    for policy, label, output, state in specs:
        repeats = []
        for rep in (0, 1):
            surfaces = [result['surfaces'][f'{policy}/repeat-{rep}/{name}'] for name in (output, state)]
            for surf, total in zip(surfaces, (64512, 6912)):
                assert surf['uncovered'] == 0 and surf['pass'] + surf['fail'] == total
                assert sha(REDUCE.parent / surf['file']) == surf['sha256']
            repeats.append({'output_fail': surfaces[0]['fail'], 'state_fail': surfaces[1]['fail']})
            assert result['cycles'][f'{policy}/repeat-{rep}']['evaluated_cells'] == 71424
        assert repeats[0] == repeats[1]
        population = result['population'][policy]
        assert population['evaluated_repeated_observations'] == 142848
        assert population['outcome'] == accept['policies'][policy]
        rows.append(dict(policy=policy, label=label, **repeats[0], output_total=64512, state_total=6912,
                         verdict=population['outcome'], repeats=2, unique_cells=71424))
    assert sum(row['unique_cells'] for row in rows) == 285696
    inputs = dict(accept['inputs_sha256'])
    inputs[str(ACCEPT.relative_to(V2))] = sha(ACCEPT)
    data = {'scope': 'Synthetic recurrent-component numerical qualification; no timing/fullmodel/workload claim',
            'seed': 20260929, 'layers': 48, 'value_heads': 48, 'active_output_nodes': 28,
            'publications': 3, 'uninterrupted_update_counts': [1, 6, 11], 'processes': 1,
            'unique_cells': 285696, 'repeated_observations': 571392, 'rows': rows,
            'comparator_boundary': 'Native GPU C1 for Lumo; declared sequential software C1 for each author policy. These different floating-point conventions prevent interpreting failures as an algorithm or task-quality ranking.',
            'performance_disposition': 'No qualified four-policy timing comparison; numerical prerequisites failed',
            'original_failure_preserved': accept['original_failed_run_preserved'], 'inputs_sha256': inputs}
    OUT.mkdir(exist_ok=True)
    (OUT / 'm1-qualification.json').write_text(json.dumps(data, indent=2) + '\n')
    body = '\n'.join(f"{r['label']} & {r['output_fail']:,} & {r['state_fail']:,} & {r['verdict']} \\\\" for r in rows)
    tex = r"""% Generated by scripts/build_m1_qualification.py; source bindings in adjacent JSON.
\begin{table}[t]
\centering
\caption{Untimed recurrent-component qualification on GB10. Entries count failed cells in each repeat: 64,512 output cells and 6,912 state cells per policy. Counts are identical in both separately evaluated repeats; comparators differ as described in the text.}
\label{tab:m1-qualification}
\small
\setlength{\tabcolsep}{3pt}
\begin{tabular}{@{}lrrl@{}}
\toprule
Policy & Output failures & State failures & Result \\
\midrule
""" + body + r"""
\bottomrule
\end{tabular}
\end{table}

We additionally compare the current recurrent verifier/native replay with pinned Weaver and TreeWY components on one frozen held-out synthetic operand set (seed 20260929), spanning 48 recurrent instances and 48 value heads. The first verification covers 28 active nodes of the fixed tree. Three accepted-path publications produce an uninterrupted history of 1, 6, and 11 updates; the checks include Weaver's accepted replay and TreeWY's final deferred commit. Each policy is evaluated twice in one process with a fresh initial state for each cycle. The population comprises 71,424 unique cells per policy, or 285,696 across four policies; the 571,392 repeated observations do not increase input coverage.

A cell fixes the recurrent instance, active output node or publication, and value head; errors are reduced over its remaining output-vector or state-matrix entries. Each cell must satisfy both the frozen RMS and maximum-error bounds, $E_{C0}\leq 1.10E_{C1}+2^{-24}M_{C2}+2^{-149}$, against its specified float64 reference $C2$. Here $E$ is the RMS or maximum absolute error and $M_{C2}$ is the corresponding RMS or maximum magnitude of $C2$. For \sys{}, $C1$ is the native GPU recurrence. The author policies use our predeclared sequential software comparators, which do not emulate every tensor-core rounding operation. TreeWY retains its author normalization floor of $10^{-12}$ and \texttt{dot\_bf16=True}; Weaver verification uses TF32 with \texttt{bf16\_mode=none}, whereas its accepted replay uses FP32 elementwise updates. Weaver's preparation uses an additive normalization constant of $10^{-6}$. Its author preparation and a separately labeled local FP32-preparation variant are both reported. These preprocessing and arithmetic conventions are not silently aligned.

Table~\ref{tab:m1-qualification} records \sys{} passing all output and publication cells in both repeats. All tensors are finite, and saved outputs and states reproduce bitwise between repeats for every policy. The three comparator configurations fail their predeclared envelopes. For example, TreeWY's BF16 compact commit and its sequential comparator's FP32 outer-product updates are different floating-point computations. These failures do not establish algorithmic incorrectness or a task-quality ranking, and they preclude a qualified four-policy timing comparison here.

The artifact preserves the first collection's second-cycle initialization failure and the subsequent lifetime-only harness repair, which reuses the process-owned Backend and resets persistent buffers in place. Every previously completed cycle reproduces unchanged in the repaired collection. The result qualifies the tested recurrent component; it does not qualify full-model convolution/KV/drafter continuation or next-forward logits.
"""
    (OUT / 'm1-qualification.tex').write_text(tex)


if __name__ == '__main__':
    main()
