"""Build the bounded GDN component table from accepted, hash-bound results."""
import hashlib
import json
from pathlib import Path

V2 = Path(__file__).resolve().parents[1]
C = V2 / "experiments/review-response-20260927"
M = V2 / "p0/monitor/review-response-20260927"
N = V2 / "notes/review-response-20260927"
OUT = V2 / "results/review-response-20260927"


def read(path):
    return json.loads(path.read_text())


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    cal_accept = M / "q12b-calibration-result-acceptance.json"
    held_accept = M / "q12b-heldout-result-acceptance.json"
    assert read(held_accept)["status"] == "INDEPENDENTLY_ACCEPTED_COMPONENT_QUALIFICATION_ONLY"
    specs = [
        ("Calibration", C / "runs/q1.2b/q12b-calibration-retry-20260928T010045Z/summary.v2.json",
         N / "raw-audit-q12b-retry/extra-tensors-and-output-differences.json",
         "68408fc1f530ca7f8de37eb4689f5becc541adfea0b2a21905838ce60e1141f6",
         "037917fed988550f0bbe8a81996e9f1d8e6c1c6930cac3a927069e461fe9fb7f"),
        ("Held-out", C / "runs/q1.2b-heldout-reduction/q12b-heldout-reduction-20260928T020837Z/summary.v2_2_1.json",
         N / "raw-audit-q12b-heldout/extra-tensors-and-output-differences.json",
         "a1a52aaf0ab290647865873e805646dcf3d87f5e3480132da8c6489c31951a71",
         "b8cfc11d22d4028f21279f3a9d36c149d04580f9178cdd1265a1bbf787423003"),
    ]
    rows, inputs = [], {str(p.relative_to(V2)): sha(p) for p in [cal_accept, held_accept]}
    for label, summary_path, audit_path, summary_sha, audit_sha in specs:
        assert sha(summary_path) == summary_sha
        assert sha(audit_path) == audit_sha
        summary, audit = read(summary_path), read(audit_path)
        assert not any(summary["findings"].values())
        assert summary["cases_expected"] == 5760
        assert summary["process_independence"]["independent"]
        for process in ["A", "B"]:
            assert summary["case_verdicts"][process] == {"PASS": 5760}
        assert all(row["findings"]["published_equals_native_chain_bitwise_all"] for row in summary["rows"])
        assert len(summary["rows"]) == 2
        assert summary["policy"]["sha256"] == "4a103df013439ae02977d10a42c3cf2eeb916a7dcb1a61c19e6b929da620f7b3"
        inputs.update({str(p.relative_to(V2)): sha(p) for p in [summary_path, audit_path]})
        rows.append({"block": label, "operand_sets": 2, "instances_per_set": 48,
                     "output_bitwise": 3072 - audit["nonbitwise_output_case_count"], "output_total": 3072,
                     "state_bitwise": 2688, "state_total": 2688, "paired_pass": 5760,
                     "cases_total": 5760, "fresh_processes": 2, "repeats": 2})
    assert rows[0]["output_bitwise"] == 3004 and rows[1]["output_bitwise"] == 3018
    OUT.mkdir(parents=True, exist_ok=True)
    data = {"scope": "Synthetic GDN verification and accepted recurrent publication only; no full-model or performance result",
            "denominator": "Per block and process: 2 operand sets x 48 instances x (32 physical output rows + 28 publication paths); repeats/processes do not add input coverage",
            "inputs_sha256": inputs, "rows": rows,
            "heldout_reduction": "Original metadata-identity refusal retained; separate authorized CPU reanalysis of unchanged tensors with unchanged numerical policy"}
    (OUT / "component-qualification.json").write_text(json.dumps(data, indent=2) + "\n")
    body = "\n".join(f"{x['block']} & {x['output_bitwise']:,}/{x['output_total']:,} & {x['state_bitwise']:,}/{x['state_total']:,} & {x['paired_pass']:,}/{x['cases_total']:,} \\\\" for x in rows)
    tex = r"""% Generated by scripts/build_component_qualification.py; inputs in adjacent JSON.
\begin{table}[t]
\centering
\caption{GDN component checks on GB10. Bitwise columns compare with the native chain; the paired rule compares both implementations with a float64 reference. Counts are per block and process.}
\label{tab:gdn-component}
\small
\setlength{\tabcolsep}{3pt}
\begin{tabular}{@{}lrrr@{}}
\toprule
Operand sets & \shortstack{BF16 output\\bitwise} & \shortstack{FP32 state\\bitwise} & \shortstack{Paired rule\\passed} \\
\midrule
""" + body + r"""
\bottomrule
\end{tabular}
\end{table}

We test GDN verification and accepted recurrent-state publication on two calibration and two held-out synthetic operand sets. Each set supplies 48 recurrent instances with the evaluated tree geometry: 32 physical output rows, including padding, and 28 accepted publication paths. Each block runs twice in each of two fresh processes. These repetitions check reproducibility; they do not increase the number of distinct inputs.

For each head, we compare both implementations with a float64 recurrence. The rule, frozen before candidate evaluation, requires both root-mean-square and maximum absolute errors to satisfy
\begin{equation}
 E_{\mathrm{tree}} \leq 1.10 E_{\mathrm{native}} + 2^{-24} M_{64} + 2^{-149},
\end{equation}
where $M_{64}$ is the corresponding root-mean-square or maximum magnitude of the reference. Table~\ref{tab:gdn-component} reports all enumerated cases passing in both processes. All published recurrent states are bitwise equal to the native chain, while 68 calibration and 54 held-out output tensors differ in BF16 rounding. Native and candidate results reproduce bitwise across repeats and processes.

Calibration controls detect sibling substitution, swapped state rings, and stale publication metadata. Poisoning an off-path branch leaves the tested selected-path state unchanged, and a zero-replay control is rejected. These results support the tested GDN scan and recurrent publication mechanism. Complete convolution/KV continuation and next-forward model decisions require the separate full-model qualification.
"""
    (OUT / "component-qualification.tex").write_text(tex)


if __name__ == "__main__":
    main()
